CREATE TABLE women_measurement (
    id INT PRIMARY KEY AUTO_INCREMENT,
    shoulder DECIMAL(10,2),
    bust DECIMAL(10,2),
    waist DECIMAL(10,2),
    armhole DECIMAL(10,2),
    sleeve_length DECIMAL(10,2),
    sleeve_opening DECIMAL(10,2),
    full_length DECIMAL(10,2),
    hip DECIMAL(10,2),
    thigh DECIMAL(10,2),
    inseam DECIMAL(10,2),
    outseam DECIMAL(10,2),
    knee DECIMAL(10,2),
    ankle DECIMAL(10,2),
    shoulder_to_waist DECIMAL(10,2),
    skirt_length DECIMAL(10,2),
    apex_point DECIMAL(10,2),
    neck_depth_front DECIMAL(10,2),
    neck_depth_back DECIMAL(10,2),
    side_split_height DECIMAL(10,2),
    cross_back DECIMAL(10,2),
    upper_bust DECIMAL(10,2),
    under_bust DECIMAL(10,2),
    arm_length DECIMAL(10,2),
    wrist DECIMAL(10,2),
    ai_confidence VARCHAR(20),
    order_id VARCHAR(100)
);